git:
  remoteRepository: "${REPOSITORY}"
  localRepositoryRoot: "${REPOSITORY_LOCAL_CACHE}"
  privateKeyFile: "${PRIVATE_KEY_FILE}"
  ignoreInsecureHosts: true
  httpAuthUsername: "${HTTPS_AUTH_USERNAME}"
  httpAuthPassword: "${HTTPS_AUTH_PASSWORD}"

rabbitmq:
  vhostPrefix: "${RABBITMQ_VHOST_PREFIX}"

cassandra:
  password: "${CASSANDRA_PASS}"
  keyspacePrefix: "${CASSANDRA_KEYSPACE_PREFIX}"

kubernetes:
  useCustomConfig: false
  namespacePrefix: "${K8S_NAMESPACE_PREFIX}"

  ingress: "${K8S_INGRESS}"
  configMaps:
    rabbitmq: "${K8S_CONFIG_MAP_RABBITMQ}"
    cassandra: "${K8S_CONFIG_MAP_CASSANDRA}"
    logging: "${K8S_CONFIG_MAP_LOGGING}"
  secretNames:
    - "chart-secrets"
    - "git-chart-creds"
    - "th2-core"
    - "th2-solution"
    - "cassandra"
    - "rabbitmq"
